In [1]:
import numpy as np

In [2]:
l=[245,345,987,876,897]
l

[245, 345, 987, 876, 897]

In [3]:
a=np.array([l])
a

array([[245, 345, 987, 876, 897]])

In [4]:
a[0]


array([245, 345, 987, 876, 897])

In [5]:
a[2:]

array([], shape=(0, 5), dtype=int64)

In [6]:
a=np.array(l)
a

array([245, 345, 987, 876, 897])

In [7]:
a[1]

345

In [8]:
b=a[2:4]
b

array([987, 876])

In [9]:
b[:]=111
a

array([245, 345, 111, 111, 897])